version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./jaindb.sln && dotnet publish ./jaindb.sln -c Release -o ./obj/Docker/publish"
